# Generated by Django 3.1.5 on 2021-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_auto_20200821_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='emp_city',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='emp_prob',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
