# Generated by Django 3.1.5 on 2021-05-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0004_emp_emp_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
