# Generated by Django 3.2 on 2021-05-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0005_auto_20210501_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
